create table roles (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table users (enabled bit not null, id bigint not null auto_increment, token_expiration datetime(6), claim_token varchar(255), password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (roles_id bigint not null, users_id bigint not null) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users_roles add constraint FKa62j07k5mhgifpp955h37ponj foreign key (roles_id) references roles (id);
alter table users_roles add constraint FKml90kef4w2jy7oxyqv742tsfc foreign key (users_id) references users (id);
create table roles (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table users (enabled bit not null, id bigint not null auto_increment, token_expiration datetime(6), claim_token varchar(255), password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (roles_id bigint not null, users_id bigint not null) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users_roles add constraint FKa62j07k5mhgifpp955h37ponj foreign key (roles_id) references roles (id);
alter table users_roles add constraint FKml90kef4w2jy7oxyqv742tsfc foreign key (users_id) references users (id);
create table roles (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table users (enabled bit not null, id bigint not null auto_increment, token_expiration datetime(6), claim_token varchar(255), password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (roles_id bigint not null, users_id bigint not null) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users_roles add constraint FKa62j07k5mhgifpp955h37ponj foreign key (roles_id) references roles (id);
alter table users_roles add constraint FKml90kef4w2jy7oxyqv742tsfc foreign key (users_id) references users (id);
create table roles (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table users (enabled bit not null, id bigint not null auto_increment, token_expiration datetime(6), claim_token varchar(255), password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (roles_id bigint not null, users_id bigint not null) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users_roles add constraint FKa62j07k5mhgifpp955h37ponj foreign key (roles_id) references roles (id);
alter table users_roles add constraint FKml90kef4w2jy7oxyqv742tsfc foreign key (users_id) references users (id);
create table roles (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table users (enabled bit not null, id bigint not null auto_increment, token_expiration datetime(6), claim_token varchar(255), password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (roles_id bigint not null, users_id bigint not null) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users_roles add constraint FKa62j07k5mhgifpp955h37ponj foreign key (roles_id) references roles (id);
alter table users_roles add constraint FKml90kef4w2jy7oxyqv742tsfc foreign key (users_id) references users (id);
create table roles (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table users (enabled bit not null, id bigint not null auto_increment, token_expiration datetime(6), claim_token varchar(255), password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (roles_id bigint not null, users_id bigint not null) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users_roles add constraint FKa62j07k5mhgifpp955h37ponj foreign key (roles_id) references roles (id);
alter table users_roles add constraint FKml90kef4w2jy7oxyqv742tsfc foreign key (users_id) references users (id);
create table roles (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table users (enabled bit not null, id bigint not null auto_increment, token_expiration datetime(6), claim_token varchar(255), password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (roles_id bigint not null, users_id bigint not null) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users_roles add constraint FKa62j07k5mhgifpp955h37ponj foreign key (roles_id) references roles (id);
alter table users_roles add constraint FKml90kef4w2jy7oxyqv742tsfc foreign key (users_id) references users (id);
create table roles (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table users (enabled bit not null, id bigint not null auto_increment, token_expiration datetime(6), claim_token varchar(255), password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (roles_id bigint not null, users_id bigint not null) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users_roles add constraint FKa62j07k5mhgifpp955h37ponj foreign key (roles_id) references roles (id);
alter table users_roles add constraint FKml90kef4w2jy7oxyqv742tsfc foreign key (users_id) references users (id);
create table roles (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table users (enabled bit not null, id bigint not null auto_increment, token_expiration datetime(6), claim_token varchar(255), password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (roles_id bigint not null, users_id bigint not null) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users_roles add constraint FKa62j07k5mhgifpp955h37ponj foreign key (roles_id) references roles (id);
alter table users_roles add constraint FKml90kef4w2jy7oxyqv742tsfc foreign key (users_id) references users (id);
create table roles (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table users (enabled bit not null, id bigint not null auto_increment, token_expiration datetime(6), claim_token varchar(255), password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (roles_id bigint not null, users_id bigint not null) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users_roles add constraint FKa62j07k5mhgifpp955h37ponj foreign key (roles_id) references roles (id);
alter table users_roles add constraint FKml90kef4w2jy7oxyqv742tsfc foreign key (users_id) references users (id);
create table roles (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table users (enabled bit not null, id bigint not null auto_increment, token_expiration datetime(6), claim_token varchar(255), password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (roles_id bigint not null, users_id bigint not null) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users_roles add constraint FKa62j07k5mhgifpp955h37ponj foreign key (roles_id) references roles (id);
alter table users_roles add constraint FKml90kef4w2jy7oxyqv742tsfc foreign key (users_id) references users (id);
create table roles (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table users (enabled bit not null, id bigint not null auto_increment, token_expiration datetime(6), claim_token varchar(255), password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (roles_id bigint not null, users_id bigint not null) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users_roles add constraint FKa62j07k5mhgifpp955h37ponj foreign key (roles_id) references roles (id);
alter table users_roles add constraint FKml90kef4w2jy7oxyqv742tsfc foreign key (users_id) references users (id);
create table roles (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table users (enabled bit not null, id bigint not null auto_increment, token_expiration datetime(6), claim_token varchar(255), password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (roles_id bigint not null, users_id bigint not null) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users_roles add constraint FKa62j07k5mhgifpp955h37ponj foreign key (roles_id) references roles (id);
alter table users_roles add constraint FKml90kef4w2jy7oxyqv742tsfc foreign key (users_id) references users (id);
create table roles (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table users (enabled bit not null, id bigint not null auto_increment, token_expiration datetime(6), claim_token varchar(255), password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (roles_id bigint not null, users_id bigint not null) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users_roles add constraint FKa62j07k5mhgifpp955h37ponj foreign key (roles_id) references roles (id);
alter table users_roles add constraint FKml90kef4w2jy7oxyqv742tsfc foreign key (users_id) references users (id);
create table roles (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table users (enabled bit not null, id bigint not null auto_increment, token_expiration datetime(6), claim_token varchar(255), password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (roles_id bigint not null, users_id bigint not null) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users_roles add constraint FKa62j07k5mhgifpp955h37ponj foreign key (roles_id) references roles (id);
alter table users_roles add constraint FKml90kef4w2jy7oxyqv742tsfc foreign key (users_id) references users (id);
create table roles (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table users (enabled bit not null, id bigint not null auto_increment, token_expiration datetime(6), claim_token varchar(255), password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (roles_id bigint not null, users_id bigint not null) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users_roles add constraint FKa62j07k5mhgifpp955h37ponj foreign key (roles_id) references roles (id);
alter table users_roles add constraint FKml90kef4w2jy7oxyqv742tsfc foreign key (users_id) references users (id);
create table roles (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table users (enabled bit not null, id bigint not null auto_increment, token_expiration datetime(6), claim_token varchar(255), password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (roles_id bigint not null, users_id bigint not null) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users_roles add constraint FKa62j07k5mhgifpp955h37ponj foreign key (roles_id) references roles (id);
alter table users_roles add constraint FKml90kef4w2jy7oxyqv742tsfc foreign key (users_id) references users (id);
create table roles (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table users (enabled bit not null, id bigint not null auto_increment, token_expiration datetime(6), claim_token varchar(255), password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (roles_id bigint not null, users_id bigint not null) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users_roles add constraint FKa62j07k5mhgifpp955h37ponj foreign key (roles_id) references roles (id);
alter table users_roles add constraint FKml90kef4w2jy7oxyqv742tsfc foreign key (users_id) references users (id);
create table roles (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table users (enabled bit not null, id bigint not null auto_increment, token_expiration datetime(6), claim_token varchar(255), password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (roles_id bigint not null, users_id bigint not null) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users_roles add constraint FKa62j07k5mhgifpp955h37ponj foreign key (roles_id) references roles (id);
alter table users_roles add constraint FKml90kef4w2jy7oxyqv742tsfc foreign key (users_id) references users (id);
create table roles (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table users (enabled bit not null, id bigint not null auto_increment, token_expiration datetime(6), claim_token varchar(255), password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (roles_id bigint not null, users_id bigint not null) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users_roles add constraint FKa62j07k5mhgifpp955h37ponj foreign key (roles_id) references roles (id);
alter table users_roles add constraint FKml90kef4w2jy7oxyqv742tsfc foreign key (users_id) references users (id);
create table roles (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table users (enabled bit not null, id bigint not null auto_increment, token_expiration datetime(6), claim_token varchar(255), password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (roles_id bigint not null, users_id bigint not null) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users_roles add constraint FKa62j07k5mhgifpp955h37ponj foreign key (roles_id) references roles (id);
alter table users_roles add constraint FKml90kef4w2jy7oxyqv742tsfc foreign key (users_id) references users (id);
